# Starter pipeline


# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main


pool:
  vmImage: ubuntu-latest

steps:
- task: CMake@1
  inputs:
    # workingDirectory: main/build
    runInsideShell: true
- task:
    inputs:
        script: |
                git clone https://github.com/llvm/llvm-project.git
                cd llvm-project
                mkdir build
                cd build 
                cmake -G Ninja -DLLVM_ENABLE_PROJECTS="clang;libcxx;libcxxabi" ../llvm
                cmake --build . --target install
        workingDirectory: /
  displayName: 'LLVM SETUP'


- script: |
# sudo apt-get update -y
    # sudo apt-get install -y llvm ninja-build
          # sudo apt install clang-6.0
          # clang --version
          mkdir build 
          cd build 
          cmake -G Ninja .. 
          cmake --build .


  displayName: 'build '