# Starter pipeline


# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main


pool:
  vmImage: ubuntu-latest

steps:
- task: CMake@1
  inputs:
    # workingDirectory: main/build
    runInsideShell: true

- task: LLVM@1
    inputs:
        script: |
                wget https://github.com/llvm/llvm-project/releases/download/llvmorg-11.1.0/clang+llvm-11.1.0-x86_64-linux-gnu-ubuntu-16.04.tar.xz
                tar -xvf "clang+llvm-11.1.0-x86_64-linux-gnu-ubuntu-16.04.tar.xz"
                cd clang+llvm-11.1.0-x86_64-linux-gnu-ubuntu-16.04
                pwd
    workingDirectory: /
    runInsideShell: true
  displayName: 'LLVM SETUP'


- script: |
          mkdir build 
          cd build 
          cmake -G Ninja .. 
          cmake --build .
  displayName: 'build '