# Starter pipeline


# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:


pool:
  vmImage: ubuntu-latest

steps:
- task: CMake@1
  inputs:
    # workingDirectory: main/build
    runInsideShell: true


- script: |
          wget https://github.com/llvm/llvm-project/releases/download/llvmorg-11.1.0/clang+llvm-11.1.0-x86_64-linux-gnu-ubuntu-16.04.tar.xz
          tar -xvf "clang+llvm-11.1.0-x86_64-linux-gnu-ubuntu-16.04.tar.xz"
          cd clang+llvm-11.1.0-x86_64-linux-gnu-ubuntu-16.04
          cd bin
          sudo cp -r ./* ../../../../../../../usr/local/bin && rm -R ./* 
          cd ..
          cd include 
          sudo cp -r ./* ../../../../../../../usr/local/include && rm -R ./*
          cd ..
          cd lib 
          sudo cp -r ./* ../../../../../../../usr/local/lib && rm -R ./*
          cd ..
          cd share 
          sudo cp -r ./* ../../../../../../../usr/local/share && rm -R ./* 
          cd ..
          cd libexec
          sudo cp -r ./* ../../../../../../../usr/libexec && rm -R ./*
  displayName: 'LLVM SETUP'

- script: |
          cd build
          cmake ..
          cmake --build .
  displayName: 'build '