# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'LLVM SETUP AND CLANG SETUP'

- script: |
          sudo apt-get update -y
          sudo apt-get install -y llvm
          sudo apt install clang-6.0
          clang --version
  displayName: 'LLVM SetUp'